# http://jekyllthemes.org/themes/basic/
# Blog settings
#permalink: /blog/:title


# My variables
locale: "en"
title: "Thomas Vogel"
title_separator: "-"
name: "Thomas Vogel"
email: "thomas.vogel (at) informatik.hu-berlin.de"
description: "Personal Website of Thomas Vogel, Software Engineering Researcher at Humboldt University Berlin, Germany."
url: "https://thomas-vogel.github.io"
# baseurl: #"/mypage"
repository: "thomas-vogel/thomas-vogel.github.io"
twitter: "https://twitter.com/tomvog"
twitter_handle: "@tomvog"
mastodon: "https://mastodon.acm.org/@tomvog"
mastodon_handle: "@tomvog@mastodon.acm.org"

# File management
include:
  - .htaccess
  - _pages
exclude: ["README.md", "LICENSE"]


## Sass
# sass:
#  style: :compressed
#  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
